apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
# Core Read
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","watch","list"]

# CRD Read
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get","list","watch"]

# Framework: admission webhook configuration management.
- apiGroups: ["admissionregistration.k8s.io/v1", "admissionregistration.k8s.io/v1beta1"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["create", "patch"]

# Events  
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

# Kopf
- apiGroups: ["kopf.dev"]
  resources: ["clusterkopfpeerings"]
  verbs: ["list", "watch", "patch", "get"]

# Permissions for secretsdistributions
- apiGroups: ["xlscsde.nhs.uk"]
  resources: ["secretsdistributions", "secretsdistributions/status"]
  verbs: ["get","watch","list","patch","create","update"]

- apiGroups: [""]
  resources: ["secrets", "secrets/status"]
  verbs: ["get","watch","list","patch","create","update"]