apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretsdistributions.xlscsde.nhs.uk
spec:
  scope: Namespaced
  group: xlscsde.nhs.uk
  names:
    kind: SecretsDistribution
    plural: secretsdistributions
    singular: secretsdistribution
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: 
                name:
                  type: string
                  description: The Name of the secret to generate
                type:
                  type: string
                  description: The type of secret
                  default: Opaque
                secrets:
                  type: array
                  description: A list of secrets to create
                  items:
                    type: object
                    properties:
                      from:
                        type: string
                        description: The name of the original secret being copied
                      to:
                        type: string
                        description: The key of the individual being created
                      
                      
            status:
              type: object
              properties:
                statusText:
                  type: string
                  description: The current status in human readable format
                lastUpdated:
                  type: string
                  description: A timestamp for when the secret was last updated

      additionalPrinterColumns:
      - name: Status
        type: string
        jsonPath: .status.statusText
      - name: LastUpdated
        type: string
        jsonPath: .status.lastUpdated